services:
  mq:
    image: rabbitmq:3.13
    container_name: mq
    ports:
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  fitlog_api_gateway:
    container_name: fitlog_api_gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    env_file:
      - ./api-gateway/.env.compose
    depends_on:
      - db
  fitlog_core_service:
    container_name: fitlog_core_service
    build:
      context: ./backend
    ports:
      - "8082:8082"
    env_file:
      - ./backend/.env.compose
    depends_on:
      - db
  fitlog_auth_service:
    container_name: fitlog_auth_service
    build:
      context: ./auth-service
    ports:
      - "8081:8081"
    env_file: ./auth-service/.env.compose
    depends_on:
      - db
volumes:
  pgdata:
